Super15Rugby/Models/Result.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Super15Rugby.Models
{
    public class Result
    {
        public int id { get; set; }
        public string TeamOne { get; set; }
        public string TeamOneScore { get; set; }
        public string TeamTwo { get; set; }
        public string TeamTwoScore { get; set; }
        public string MatchDate { get; set; }
    }

    public class DBResult : Result 
    {
        public int Round;
    }

    public class Week
    {
        public int weekNumber { get; set; }
        public List<DBResult> results { get; set; }

        public Week() 
        {
            results = new List<DBResult>();
        }
    }

    public class SuperRugbyYear
    {
        public int year { get; set; }
        public List<Week> weeks { get; set; }

        public SuperRugbyYear() 
        {
            weeks = new List<Week>();
        }
    }
}

Super15Rugby/Models/Table.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;

namespace Super15Rugby.Models
{
    public class Table
    {
        public List<Team> Teams { get; set; }
    }
}

Super15Rugby/Models/Team.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;

namespace Super15Rugby.Models
{
    public enum Conference { Australia, NewZealand, SouthAfrica}

    public class Team
    {
        //public string TeamName { get; set; }
        //public Conference Conference { get; set; }
        //public int Played { get; set; }
        //public int Wins { get; set; }
        //public int Losses { get; set; }
        //public int Draws { get; set; }
        //public int PointsFor { get; set; }
        //public int PointsAgainst { get; set; }
        //public int PointsDifferential { get; set; }
        //public int BonusPoints { get; set; }
        //public int TablePoints { get; set; }
        public string ConferenceName;
        public string TeamName;
        public int Played;
        public int Wins;
        public int Losses;
        public int Draws;
        public int PointsFor;
        public int PointsAgainst;
        public int PointsDifferential;
        public int BonusPoints;
        public int TablePoints;
    }
}

Super15Rugby/Models/ViewModels/ResultsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Super15Rugby.Models.ViewModels
{
    public class YearResults 
    {
        public List<DBResult> results;
        public int year;

        public YearResults() 
        {
            results = new List<DBResult>();
        }
    }
    public class ResultsViewModel
    {
        public List<SuperRugbyYear> years;
        
        public ResultsViewModel() 
        {
            years = new List<SuperRugbyYear>();
        }
    }
}

Super15Rugby/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Super15Rugby.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Super15Rugby/Controllers/ResultsController.cs
using Super15Rugby.DataLayer;
using Super15Rugby.Models;
using Super15Rugby.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Super15Rugby.Controllers
{
    public class ResultsController : Controller
    {
        // GET: Results
        public ActionResult Index()
        {
            var yearsToQueryFor = GetYearsToQueryFor();
            var resultDataLayer = new ResultsDataLayer();
            var viewModel = new ResultsViewModel();

            foreach (var year in yearsToQueryFor) 
            {
                viewModel.years.Add(resultDataLayer.GetSuperRugbyResults(year));
            }
            
            return View("AllResults", viewModel);
        }

        private List<int> GetYearsToQueryFor() 
        {
            var latestSuperRugbyYear = Int32.Parse(ConfigurationManager.AppSettings["LatestSuperRugbyYear"]);
            var yearsToGet = new List<int>();
            yearsToGet.Add(2006);

            while (yearsToGet.Max() < latestSuperRugbyYear)
            {
                yearsToGet.Add(yearsToGet.Max() + 1);
            }

            return yearsToGet;
        }
    }
}

Super15Rugby/Controllers/SuperRugbyTableController.cs
using Newtonsoft.Json;
using Super15Rugby.DataLayer;
using Super15Rugby.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;

namespace Super15Rugby.Controllers
{
    public class SuperRugbyTableController : Controller
    {
        // GET: Table
        public ActionResult Index()
        {
            
            return View(new SuperRugbyTableDataLayer().GetTable());
        }
    }
}

Super15Rugby/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Super15Rugby/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Super15Rugby/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Super15Rugby/Views/Results/AllResults.cshtml
@model Super15Rugby.Models.ViewModels.ResultsViewModel

@{
    ViewBag.Title = "Index";
}

<link rel="stylesheet" href="~/Scripts/tablesorter-master/css/theme.blue.css">

Year: 
<div class="btn-group-lg" role="group" aria-label="...">
    @foreach (var year in Model.years)
    {
        <button type="button" class="yearSelector btn btn-default">@year.year</button>
    }
</div>

<div style="clear:both"></div>
Week:
<div class="btn-group-sm" role="group" aria-label="...">
    @foreach (var week in Model.years[0].weeks)
    {
        <button type="button" class="btn btn-default">@week.weekNumber</button>
    }
</div>

<table id="myTable" class="tablesorter">
    <thead>
        <tr>
            <th class="filter-select">Home Team</th>
            <th>Score</th>
            <th class="filter-select">Away Team</th>
            <th>Score</th>
            <th>Match Date</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var year in Model.years)
        {

            foreach (var week in year.weeks)
            {

                foreach (var result in week.results)
                {
                    <tr>
                        <td>@result.TeamOne</td>
                        <td>@result.TeamOneScore</td>
                        <td>@result.TeamTwo</td>
                        <td>@result.TeamTwoScore</td>
                        <td>@result.MatchDate</td>
                    </tr>
                }

            }

        }
    </tbody>
</table>
<script type="text/javascript" src="~/Scripts/jquery-1.10.2.min.js"></script>
<script type="text/javascript" src="~/Scripts/tablesorter-master/js/jquery.tablesorter.js"></script>
<script type="text/javascript" src="~/Scripts/tablesorter-master/js/jquery.tablesorter.widgets.js" ></script> 
<script>
    $(document).ready(function () {
        $("#myTable").tablesorter({
            theme: 'blue',
            widgets: ["zebra", "filter"]
        });
        
        $('.yearSelector').each(function () {
            if (this.innerHTML == '2006') {
                $(this).addClass('active');
            }
        });

        function setYearSelectorActive() {
            $('.yearSelector').removeClass('active');
            $('.yearSelector').removeAttr('checked');
            $(this).attr('checked', 'checked');
            $(this).addClass('active');
        }

        $('.yearSelector').click(setYearSelectorActive);

    }

);
</script>

Super15Rugby/Views/Results/Index.cshtml
@model Super15Rugby.Models.ViewModels.ResultsViewModel

@{
    ViewBag.Title = "Index";
}
    @foreach (var year in Model.years)
    {
        <h1>Year: @year.year</h1>
        
        foreach (var week in year.weeks)
        {
            <h2>Week: @week.weekNumber</h2>
    <table class="table table-bordered">
        <tr>
            <th>Home Team</th>
            <th>Score</th>
            <th>Away Team</th>
            <th>Score</th>
            <th>Match Date</th>
        </tr>
        @foreach (var result in week.results)
        {
            <tr>
                <td>@result.TeamOne</td>
                <td>@result.TeamOneScore</td>
                <td>@result.TeamTwo</td>
                <td>@result.TeamTwoScore</td>
                <td>@result.MatchDate</td>
            </tr>
        }
    </table>
        }

    }

        

Super15Rugby/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @*@Scripts.Render("~/bundles/modernizr")*@
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Super 15", "Index", "SuperRugbyTable", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Table", "Index", "SuperRugbyTable")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @*@Scripts.Render("~/bundles/bootstrap")*@
    @RenderSection("scripts", required: false)
</body>
</html>

Super15Rugby/Views/SuperRugbyTable/Index.cshtml
@model Super15Rugby.Models.Table
@{
    ViewBag.Title = "Index";
}

<h2>Super 15 Table</h2>

<table class="table table-bordered">
    @{var position = 1;}
    <tr>
        <th>Position</th>
        <th>Team</th>
        <th>Conference</th>
        <th>Played</th>
        <th>Won</th>
        <th>Loss</th>
        <th>Drawn</th>
        <th>Points For</th>
        <th>Points Against</th>
        <th>Points Differential</th>
        <th>Bonus Points</th>
        <th>Total Points</th>
    </tr>
    @foreach (var t in Model.Teams)
    {
        var backGroundColour = "info";
        if (position <= 3)
        {
            backGroundColour = "success";
        }
        else if (position <= 6)
        {
            backGroundColour = "danger";
        }
        <tr class="@backGroundColour">
            <td>@position</td>
            <td>@t.TeamName</td>
            <td>@t.ConferenceName</td>
            <td>@t.Played</td>
            <td>@t.Wins</td>
            <td>@t.Losses</td>
            <td>@t.Draws</td>
            <td>@t.PointsFor</td>
            <td>@t.PointsAgainst</td>
            <td>@t.PointsDifferential</td>
            <td>@t.BonusPoints</td>
            <td>@t.TablePoints</td>
        </tr>

        position++;
    }
</table>